<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <jvmArguments>
            -Dhttps.proxyHost=${PROXY_HOST}
            -Dhttps.proxyPort=${PROXY_PORT}
            -Dhttp.proxyHost=${PROXY_HOST}
            -Dhttp.proxyPort=${PROXY_PORT}
            -Dhttp.nonProxyHosts=localhost|127.0.0.1
            -Djava.security.auth.login.config=
            -Djavax.security.auth.useSubjectCredsOnly=false
            -Dsun.security.krb5.debug=false
        </jvmArguments>
        <excludes>
            <exclude>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
            </exclude>
        </excludes>
    </configuration>
</plugin>
